# Generated by Django 4.2.1 on 2023-06-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_activated_user_activation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activated',
            new_name='is_activated',
        ),
    ]
